export const ALL_COUPON_REQUEST = "ALL_COUPON_REQUEST"
export const ALL_COUPON_SUCCESS = "ALL_COUPON_SUCCESS"
export const ALL_COUPON_FAIL = "ALL_COUPON_FAIL"


export const DELETE_COUPON_REQUREST = "DELETE_COUPON_REQUREST"
export const DELETE_COUPON_SUCCESS = "DELETE_COUPON_SUCCESS"
export const DELETE_COUPON_RESET = "DELETE_COUPON_RESET"
export const DELETE_COUPON_FAIL = "DELETE_COUPON_FAIL"


export const CREATE_COUPON_SUCCESS = "CREATE_COUPON_SUCCESS"
export const CREATE_COUPON_REQUEST = "CREATE_COUPON_REQUEST"
export const CREATE_COUPON_RESET = "CREATE_COUPON_RESET"
export const CREATE_COUPON_FAIL = "DELETE_COUPON_FAIL"


export const CLEAR_ERRORS = "CLEAR_ERROR"